### ISSUE TITLE
use planet.tar memory mapped

### ISSUE THREAD

**Issue by kevinkreiser** [valhalla/chef-valhalla#128]
make sure to let others know of this change and carefully coordinate the roll out
- [x] update cut_tiles.sh to tar the tiles properly and to upload the tar to s3 instead of the tgz
- [x] use awscli instead of custom python to do the uploading, but have to cull old stuffs
- [x] update get_routing_tiles.rb recipe to not unpack the tiles and to use awscli to download from s3
- [ ] to do deploy this we'll need to disable and stop the tile cutting cron, update the cookbooks, and reenable it
- [x] add edge dumping to the end of tile cutting and upload to s3, it only takes a few minutes and is useful for others

**Comment by missinglink** [comment]
:+1: for edge dumping, it's important for us to have fresh data for https://github.com/pelias/interpolation
