### ISSUE TITLE
Can't find path

### ISSUE THREAD

**Issue by costales** [valhalla/chef-valhalla#67]
Hi!

I have this destination, and I can't get a route to it:
https://valhalla.mapzen.com/route?json={"locations":[{"lat":52.520007,"lon":13.404954},{"lat":51.4932641,"lon":6.87927051990832}],"costing":"auto"}&api_key=valhalla-xxxxxx

Thanks in advance!

**Comment by dnesbitt61** [comment]
Looking into this. Thanks.
